db:
  host: store_db
  port: 5432
  user: root
  password: alex0000
  dbname: store_db
  sslmode: disable

minio:
  host: minio
  port: 9000
  access_key_id: SX1o3y8kcjMpN6lLjsHh
  secret_access_key: PuRrMhFaap1f3RBDd0S5pHNly9dpFYtzO2BKNg7M
  use_ssl: false
redis:
  host: redis
  port: 6379
  password: alex0000

singing_key: fdljdcsdcsv232e3cdjif

kafka:
  host: kafka
  port: 9092

app_host: 8083
